# golangci-lint configuration for ticat
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  skip-dirs:
    - bin
    - vendor

linters:
  disable-all: true
  enable:
    # Basic checks
    - gofmt
    - goimports
    - errcheck
    
issues:
  exclude-use-default: false
  # Exclude unreachable code - these are intentional in this codebase
  exclude:
    - 'unreachable code'
    - 'statement is unreachable'
