// Code generated by goyacc -o cmd.y.go cmd.y. DO NOT EDIT.

//line cmd.y:2
package parser

import __yyfmt__ "fmt"

//line cmd.y:2

import (
	"fmt"
	"strings"

	"github.com/innerr/ticat/pkg/core/model"
)

type yaccParseContext struct {
	cmdParser    *CmdParser
	envParser    *EnvParser
	cmds         *model.CmdTree
	envAbbrs     *model.EnvAbbrs
	currCmd      *model.CmdTree
	currEnvAbbrs *model.EnvAbbrs
	matchedPath  []string
	trivialLvl   int
	err          error
	isMinorErr   bool
	allowSub     bool
	rest         []string
}

//line cmd.y:28
type yySymType struct {
	yys     int
	str     string
	seg     parsedSeg
	segs    []parsedSeg
	env     model.ParsedEnv
	isEmpty bool
}

const WORD = 57346
const ENV = 57347
const SEP = 57348

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"WORD",
	"ENV",
	"SEP",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cmd.y:107

type yyLex struct {
	tokens   []yyToken
	pos      int
	result   []parsedSeg
	ctx      *yaccParseContext
	hasError bool
}

type yyToken struct {
	typ int
	str string
}

func newYYLex(tokens []yyToken, ctx *yaccParseContext) *yyLex {
	return &yyLex{
		tokens: tokens,
		pos:    0,
		ctx:    ctx,
	}
}

func (l *yyLex) Lex(lval *yySymType) int {
	if l.pos >= len(l.tokens) || l.hasError {
		return 0
	}
	tok := l.tokens[l.pos]
	l.pos++
	lval.str = tok.str
	return tok.typ
}

func (l *yyLex) Error(s string) {
	l.hasError = true
}

func (l *yyLex) SetResult(segs []parsedSeg) {
	l.result = segs
}

func (l *yyLex) ProcessWord(word string) parsedSeg {
	ctx := l.ctx

	if ctx.allowSub && ctx.currCmd != nil {
		sub := ctx.currCmd.GetSub(word)
		if sub != nil {
			ctx.currCmd = sub
			if ctx.currEnvAbbrs != nil {
				ctx.currEnvAbbrs = ctx.currEnvAbbrs.GetSub(word)
			}
			ctx.matchedPath = append(ctx.matchedPath, word)
			ctx.allowSub = false
			return parsedSeg{Type: parsedSegTypeCmd, Val: model.MatchedCmd{Name: word, Cmd: sub}}
		}
	}

	if ctx.allowSub {
		errStr := "unknow input '" + word + "' ..., should be sub cmd"
		ctx.err = fmt.Errorf("[CmdParser.parse] %s: %s", l.displayPath(), errStr)
		ctx.isMinorErr = false
		l.hasError = true
	}

	return parsedSeg{Type: parsedSegTypeCmd, Val: model.MatchedCmd{Name: word}}
}

func (l *yyLex) ProcessEnv(envStr string) parsedSeg {
	ctx := l.ctx
	env := parseEnvString(envStr, ctx.cmdParser.envParser)

	// Debug: print env parsing result
	// fmt.Printf("ProcessEnv: %q -> env=%v\n", envStr, env)

	if len(ctx.matchedPath) > 0 && env != nil {
		for k, v := range env {
			env[k] = model.ParsedEnvVal{
				Val:            v.Val,
				IsArg:          v.IsArg,
				IsSysArg:       v.IsSysArg,
				MatchedPath:    append(ctx.matchedPath, v.MatchedPath...),
				MatchedPathStr: strings.Join(append(ctx.matchedPath, v.MatchedPath...), ctx.cmdParser.cmdSep),
			}
		}
	}

	return parsedSeg{Type: parsedSegTypeEnv, Val: env}
}

func (l *yyLex) displayPath() string {
	ctx := l.ctx
	if len(ctx.matchedPath) == 0 {
		return ctx.cmdParser.cmdRootNodeName
	}
	return strings.Join(ctx.matchedPath, ctx.cmdParser.cmdSep)
}

func parseEnvString(s string, envParser *EnvParser) model.ParsedEnv {
	if !strings.HasPrefix(s, envParser.brackets.Left) || !strings.HasSuffix(s, envParser.brackets.Right) {
		return nil
	}

	content := s[len(envParser.brackets.Left) : len(s)-len(envParser.brackets.Right)]
	content = strings.TrimSpace(content)
	if len(content) == 0 {
		return nil
	}

	env := make(model.ParsedEnv)
	parts := splitBySep(content, envParser.kvSep)

	i := 0
	for i < len(parts) {
		part := strings.TrimSpace(parts[i])
		if i+2 < len(parts) && strings.TrimSpace(parts[i+1]) == envParser.kvSep {
			key := part
			val := strings.TrimSpace(parts[i+2])
			env[key] = model.NewParsedEnvVal(key, val)
			i += 3
		} else if i+1 < len(parts) && strings.Contains(part, envParser.kvSep) {
			kv := strings.SplitN(part, envParser.kvSep, 2)
			if len(kv) == 2 {
				env[strings.TrimSpace(kv[0])] = model.NewParsedEnvVal(strings.TrimSpace(kv[0]), strings.TrimSpace(kv[1]))
			}
			i++
		} else {
			i++
		}
	}

	return env
}

func splitBySep(s string, sep string) []string {
	var parts []string
	current := ""
	i := 0
	for i < len(s) {
		if i+len(sep) <= len(s) && s[i:i+len(sep)] == sep {
			if len(current) > 0 {
				parts = append(parts, current)
			}
			parts = append(parts, sep)
			current = ""
			i += len(sep)
		} else {
			current += string(s[i])
			i++
		}
	}
	if len(current) > 0 {
		parts = append(parts, current)
	}
	return parts
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 7

var yyAct = [...]int8{
	4, 5, 6, 3, 2, 1, 7,
}

var yyPact = [...]int16{
	-4, -1000, -4, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 5, 4, 3,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 3, 3, 3,
}

var yyR2 = [...]int8{
	0, 0, 1, 1, 2, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 4, 5, 6, -3,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 5, 6, 7, 4,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line cmd.y:46
		{
			yyVAL.segs = nil
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd.y:50
		{
			yyVAL.segs = yyDollar[1].segs
			yylex.(*yyLex).SetResult(yyVAL.segs)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd.y:57
		{
			if yyDollar[1].seg.Type == parsedSegTypeSep && len(yyVAL.segs) == 0 {
				yyVAL.segs = nil
			} else if yyDollar[1].seg.Type == parsedSegTypeEnv {
				if env, ok := yyDollar[1].seg.Val.(model.ParsedEnv); !ok || len(env) == 0 {
					yyVAL.segs = nil
				} else {
					yyVAL.segs = []parsedSeg{yyDollar[1].seg}
				}
			} else {
				yyVAL.segs = []parsedSeg{yyDollar[1].seg}
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd.y:71
		{
			if yyDollar[2].seg.Type == parsedSegTypeEnv {
				if env, ok := yyDollar[2].seg.Val.(model.ParsedEnv); !ok || len(env) == 0 {
					yyVAL.segs = yyDollar[1].segs
				} else {
					yyVAL.segs = append(yyDollar[1].segs, yyDollar[2].seg)
				}
			} else if yyDollar[2].seg.Type == parsedSegTypeSep {
				if len(yyDollar[1].segs) > 0 && yyDollar[1].segs[len(yyDollar[1].segs)-1].Type == parsedSegTypeSep {
					yyVAL.segs = yyDollar[1].segs
				} else {
					yyVAL.segs = append(yyDollar[1].segs, yyDollar[2].seg)
				}
			} else {
				yyVAL.segs = append(yyDollar[1].segs, yyDollar[2].seg)
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd.y:91
		{
			yyVAL.seg = yylex.(*yyLex).ProcessWord(yyDollar[1].str)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd.y:95
		{
			yyVAL.seg = yylex.(*yyLex).ProcessEnv(yyDollar[1].str)
			// After processing env, allow sub command
			yylex.(*yyLex).ctx.allowSub = true
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd.y:101
		{
			yyVAL.seg = parsedSeg{Type: parsedSegTypeSep, Val: nil}
			// After separator, allow sub command
			yylex.(*yyLex).ctx.allowSub = true
		}
	}
	goto yystack /* stack new state and value */
}
